const express = require('express')
const { createBlog, getDetailBlog, getAllBlogs, getAllBlogsByDoctor, updateView } = require('../controllers/blog.controller')
const { upload } = require('../middlewares/multer')
const router = express.Router()
router.post('/', upload.single('file'), createBlog)
router.get('/:id', getDetailBlog)
router.get('/', getAllBlogs)
router.post('/getblog', getAllBlogsByDoctor)
router.patch('/:blogId', updateView)
exports.blogRoutes = router